services:
  ollama:
    container_name: ollama
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    restart: unless-stopped
    volumes:
      - ./data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              count: ${OLLAMA_GPU_COUNT-1}
              driver: ${OLLAMA_GPU_DRIVER-nvidia}
    env_file:
      - .env

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    volumes:
      - ./data/open-webui:/app/backend/data
    env_file:
      - .env
