version: '2'

services:
  db:
    image: mysql:5.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
  app:
    image: php:5.6-apache
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - db
