version: '3'

services:
  teamspeak:
    image: teamspeak
    restart: unless-stopped
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    volumes:
      - ./data/ts3server:/var/ts3server
    env_file: .env
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/mysql
    env_file: .env
