version: '3'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:latest
    restart: unless-stopped
    networks:
      - wings0
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"
      - "./pterodactyl/etc/:/etc/pterodactyl/"
      - "./pterodactyl/log/:/var/log/pterodactyl/"
      - "./pterodactyl/tmp/:/tmp/pterodactyl/"
      - "./pterodactyl/lib/:/var/lib/pterodactyl/"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      - "./pterodactyl/letsencrypt/:/etc/letsencrypt/"

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
