version: '3'

services:
  openldap:
    container_name: openldap
    image: osixia/openldap:1.5.0
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./ldap:/var/lib/ldap
      - ./slapd.d:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs/
    env_file:
      - env/example.env
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "example.com"
      LDAP_DOMAIN: "ldap.example.com"
      LDAP_BASE_DN: ""
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_PROTOCOL_MIN: "3.0"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "try"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    domainname: ldap.example.com
    hostname: ldap.example.com

  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./phpldapadmin/etc/apache2/ports.conf:/etc/apache2/ports.conf
      - ./phpldapadmin/etc/apache2/sites-enabled/phpldapadmin.conf:/etc/apache2/sites-enabled/phpldapadmin.conf
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'localhost': [{'server': [{'tls': True}]}]}]"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: never
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
