version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    volumes:
       - ./etc-pihole:/etc/pihole/
       - ./etc-dnsmasq.d:/etc/dnsmasq.d/
    environment:
      TZ: America/NewYork
      DNS1: 208.67.222.222
      DNS2: 208.67.220.220
      DNSSEC: "true"
