version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      TZ: "America/NewYork"
      DNS1: 208.67.222.222
      DNS2: 208.67.220.220
      DNSSEC: "true"
    volumes:
       - ./etc-pihole:/etc/pihole/
       - ./etc-dnsmasq.d:/etc/dnsmasq.d/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "127.0.0.1:8000:80/tcp"
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
