version: '3'

services:
  db:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./db/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - db.env
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  redis:
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    build: nextcloud
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./html/:/var/www/html/
      - ./data/:/var/www/html/data/
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
    build: nextcloud-cron
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html/
      - ./data/:/var/www/html/data/
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - nextcloud
