version: '2'

services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./deCONZ:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
