version: '3'

volumes:
  cache:

services:
  apt-cacher-ng:
    container_name: apt-cacher-ng
    build: .
    restart: unless-stopped
    ports:
      - 127.0.0.1:3142:3142
    volumes:
      - ./cache:/var/cache/apt-cacher-ng
