services:
  headscale:
    image: docker.io/headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /var/run/headscale
    ports:
      - 0.0.0.0:8080:8080
      - 127.0.0.1:9090:9090
    volumes:
      - ./data/headscale/config:/etc/headscale:ro
      - ./data/headscale/lib:/var/lib/headscale
    command: serve
    healthcheck:
      test: ["CMD", "headscale", "health"]

  headplane:
    image: ghcr.io/tale/headplane:latest
    container_name: headplane
    restart: unless-stopped
    depends_on:
      headscale:
        condition: service_healthy
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./data/headplane/config/config.yaml:/etc/headplane/config.yaml:ro
      - ./data/headplane/lib:/var/lib/headplane
