up:
	docker-compose up -d

down:
	docker-compose down

restart:
	docker-compose restart

logs:
	docker-compose logs -f

shell:
	./shell.sh

rm:
	docker-compose down -v
	docker-compose rm

clean: rm

.PHONY: *
