version: '3'

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./configuration.yaml:/app/data/configuration.yaml
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
